# Generated by Django 3.2.7 on 2021-10-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
    ]
